### ISSUE TITLE
Register-PromptHook breaks posh-git prompt

### ISSUE THREAD

**Issue by rkeithhill** [vors/ZLocation#59]
The [posh-git ](https://github.com/dahlbyk/posh-git) module injects its own prompt function that provides various features including a Git status display in the prompt.  As soon as you `Import-Module ZLocation`, it breaks the posh-git prompt function i.e. the prompt degenerates to `PS>`:

![image](https://user-images.githubusercontent.com/5177512/45397558-d03fde00-b5fd-11e8-994c-86573a431862.png)

The reason it breaks is that the `Register-PromptHook` function doesn't just append `Update-ZLocation $pwd` to the front of the prompt function.  It creates a new scriptblock in the scope of the ZLocation module. 

https://github.com/vors/ZLocation/blob/2ccc541f87d98c7cfa72cee6fd423c8a195f7aac/ZLocation/ZLocation.psm1#L45-L59

This breaks posh-git because it created its prompt scriptblock within the posh-git module e.g.:

```
C:\Users\Keith
09-11 20:05:57 3> (Get-Command Prompt).Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Expand-GitCommand, Form...


C:\Users\Keith
09-11 20:06:00 4> ipmo ZLocation
PS>(Get-Command Prompt).Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        __DynamicModule_3cd9b6f8-0961-47...
```
The results in errors that prevent the posh-git prompt function, recreated in a new scriptblock, from being able to access private, module-scoped functions:
```
PS>$error
The term 'EscapeAnsiString' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
EscapeAnsiString : The term 'EscapeAnsiString' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:102 char:37
+         $global:PoshGitLastPrompt = EscapeAnsiString $prompt
+                                     ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (EscapeAnsiString:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
One possible workaround it to special case `posh-git`.  Yeah I don't think it is a great solution but it does work.  :-)  This is done by a simple check for a posh-git defined prompt function in the `Register-PromptHook` function and then injecting a scriptblock that invokes `Update-ZLocation $pwd`:
```
function Register-PromptHook
{
    param()

    # If posh-git is supplying the prompt function, inject update command via the posh-git VcsPromptStatuses hook
    $prompt = Get-Command prompt -CommandType Function -ErrorAction SilentlyContinue
    if ($prompt -and $prompt.module -and $prompt.module.name -eq 'posh-git') {
        $global:VcsPromptStatuses += { [void](Update-ZLocation $pwd) }
        return
    }
…
```
I'm definitely open to other ideas that are more widely applicable.  Ideally the PowerShell engine would expose an event that fires whenever the FileSystem provider changes location.

BTW the above solution is dependent on module import order.  It will work if ZLocation is imported **after** posh-git.  If ZLocation is imported before posh-git, then posh-git punt on modifying the prompt function because it "appears" the user has their own customized prompt.  

cc @dahlbyk

**Comment by vors** [comment]
Interesting, thank you for the detailed analyze Keith!
Maybe a slightly less special-casing could be `& (Get-Module posh-git) {[scriptblock]::Create(...)}` ? That should also evaluate the prompt in the context of posh-git, but

I'd recommend also opening a corresponding issue in posh-git.

**Comment by dahlbyk** [comment]
I'm watching this here; we can make a posh-git issue when there's a more concrete direction.

I'm certainly not opposed to making posh-git play more nicely with other modules that modify `prompt`. In this case, it may be as simple as matching a `prompt` that _ends with_ the default prompt and pulling anything that's been prepended into a `ScriptBlock` we can execute as part of posh-git's `prompt`.

On the ZLocation side, it would definitely be helpful to avoid stepping on an existing customized `prompt` function, either by checking against the default `prompt` or by checking `$prompt.module`.

https://github.com/dahlbyk/posh-git/blob/220c06f5b5685e9da381f3c6611d2afb104abc8e/src/posh-git.psm1#L21-L28

https://github.com/dahlbyk/posh-git/blob/220c06f5b5685e9da381f3c6611d2afb104abc8e/src/posh-git.psm1#L125-L129

**Comment by vors** [comment]
@dahlbyk thank you for chiming in!

Here is how ZLocation currently modifies the prompt:
https://github.com/vors/ZLocation/blob/2ccc541f87d98c7cfa72cee6fd423c8a195f7aac/ZLocation/ZLocation.psm1#L45
As you can see this is pretty harmless in itself, it simply adds a call to a function that's publicly exported into the user session (from the same ZLocation module).

As far as I understand from Keith's investigation (correct me if I'm wrong) `posh-git` calls the private functions and hence relays on the fact that prompt `[scriptblock]` got created in the module scope.

My proposition about posh-git change would be alternating the prompt registration in a way that doesn't rely on the fact that `prompt` is created in the posh-git module scope. That would allow the prompt to be later re-created from anywhere. Practically it could be implemented in different ways, i.e. exporting the functions used in the prompt as public module members.

It would have other side benefits, like allowing people to customize their prompt by using posh-git primitives as building blocks.

**Comment by dahlbyk** [comment]
The downside is posh-git exporting functions that aren't meant for public consumption. Instead of prepending `Update-ZLocation` to the existing `prompt` definition, have you calling the old prompt inside yours? Something like…

```powershell
 function Register-PromptHook 
 { 
     param() 
  
     $oldPrompt = function:\prompt 
     if( $oldPrompt.Definition -notlike '*Update-ZLocation*' ) 
     { 
         $newPrompt = @' 
 Update-ZLocation $pwd 
  
 & $oldPrompt
 '@
         Set-Content -Force -Path function:\prompt -Value ([ScriptBlock]::Create($newPrompt)) 
     } 
 } 
```

I really don't know if this will properly create a closure over `$oldPrompt`, but it seems like there should be a way?

(Please pardon typos from my phone.)

**Comment by dahlbyk** [comment]
On the other hand… what if the posh-git actual `prompt` was just (effectively):

```powershell
function prompt {
  & $GitPromptScriptBlock
}
```

**Comment by rkeithhill** [comment]
Well, what do you know?  Look what I found in PS Core 6.1!
```
function Register-PromptHook
{
    param()

    if (($PSVersionTable.PSVersion.Major -ge 6) -and ($PSVersionTable.PSVersion.Minor -ge 1)) {
        $prevHandler = $ExecutionContext.InvokeCommand.LocationChangedAction
        $ExecutionContext.InvokeCommand.LocationChangedAction = {
            param($sender, $eventArgs)
            Update-ZLocation $eventArgs.NewPath
            if ($prevHandler) {
                $prevHandler.Invoke($sender, $eventArgs)
            }
        }.GetNewClosure()

        return
    }
…
```
Works a treat!  Now just need to figure out best approach for PS < 6.1.

**Comment by vors** [comment]
Great finding!

**Comment by vors** [comment]
@rkeithhill is it fully fixed by #66 ?

**Comment by rkeithhill** [comment]
As long as you import zlocation after posh-git, yes, it should be fixed.  If you import zlocation first, posh-git will see that the prompt has been modified by the user and will not modify it.

**Comment by inputfalken** [comment]
I'm using PS 6.1 and import `posh-git` (V1.0.0) before `ZLocation` (V1.1.0)  But I still do not have a git prompt.
I'm also using `PSReadLine` (V2.0.0)

Any idea what i can do?

**Comment by rkeithhill** [comment]
When you run this command - `gcm prompt | % definition` - what output do you get?  If things are working right, you should get:
```
            Update-ZLocation $pwd
            ZLocationOrigPrompt
```
And `gcm ZlocationOrigPrompt | % definition` should spit out something like:
```
    $settings = $global:GitPromptSettings
    if (!$settings) {
        return "<`$GitPromptSettings not found> "
    }

    if ($settings.DefaultPromptEnableTiming) {
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
    }

    $origLastExitCode = $global:LASTEXITCODE
…
```

**Comment by inputfalken** [comment]
I get the following

gcm prompt | % definition

```

            Update-ZLocation $pwd
            ZLocationOrigPrompt
```
gcm ZlocationOrigPrompt | % definition
```
"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
# .Link
# https://go.microsoft.com/fwlink/?LinkID=225750
# .ExternalHelp System.Management.Automation.dll-help.xml
```

**Comment by rkeithhill** [comment]
Hmm, so the `ZlocationOrigPrompt` is the default prompt.  If you are importing `posh-git` before `zlocation` then this shouldn't be happening unless for some reason `posh-git` is changing the prompt function.  

Try this.  Start pwsh with `-noprofile` and then execute `Import-Module posh-git`.  Does that modify the prompt to show Git status?

**Comment by inputfalken** [comment]
Yes it modifies my prompt.

**Comment by rkeithhill** [comment]
And then if, in the same session, you execute `Import-Module ZLocation` the Git prompt goes away?

**Comment by inputfalken** [comment]
It stasy when with `Import-Module ZLocation` as well. 🤔

**Comment by rkeithhill** [comment]
Wait, what?  If the Git prompt stays, then it is working, right?

**Comment by inputfalken** [comment]
Well it's gone when I load my profile.

My profile can be found here: https://github.com/inputfalken/dotfiles/blob/master/powershell/Microsoft.PowerShell_profile.ps1

I have not updated it with zlocation. But otherwise it's about the same.

**Comment by rkeithhill** [comment]
Do you have anything in your other profile files?
```
$profile | fl -force


AllUsersAllHosts       : C:\Program Files\PowerShell\6\profile.ps1
AllUsersCurrentHost    : C:\Program Files\PowerShell\6\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    : C:\Users\Keith\Documents\PowerShell\profile.ps1
CurrentUserCurrentHost : C:\Users\Keith\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
Length                 : 68
```

**Comment by inputfalken** [comment]
Thanks for your help and time 👍

That's a very good question 🙂.

I currently do not have access to my computer. I can check it tommorow.

**Comment by inputfalken** [comment]
Thank you so much `C:\Users\Keith\Documents\PowerShell\profile.ps1` also imported ZLocation 👍 .

**Comment by inputfalken** [comment]
Which one of `AllUsersAllHosts` or `AllUsersCurrentHost` is best practice to have my profile script in?

**Comment by rkeithhill** [comment]
I rarely used AllUsers*.  I put stuff that I'm confident will run in any host in addition tothe console host e.g. ISE, VSCode's PowerShell extension, etc inside `CurrentUserAllHosts`.  Anything that is host specific, like registering VSCode editor commands, goes in the host-specific profile (CurrentUserCurrentHost) which is `Microsoft.VSCode_profile.ps1` for the PS integrated console in VSCode.

**Comment by inputfalken** [comment]
Oh ye I meant those two 😜 thanks for your input.
